require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/user_transactions', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # UserTransaction. As you add validations to UserTransaction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      UserTransaction.create! valid_attributes
      get user_transactions_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      user_transaction = UserTransaction.create! valid_attributes
      get user_transaction_url(user_transaction)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_user_transaction_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      user_transaction = UserTransaction.create! valid_attributes
      get edit_user_transaction_url(user_transaction)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new UserTransaction' do
        expect do
          post user_transactions_url, params: { user_transaction: valid_attributes }
        end.to change(UserTransaction, :count).by(1)
      end

      it 'redirects to the created user_transaction' do
        post user_transactions_url, params: { user_transaction: valid_attributes }
        expect(response).to redirect_to(user_transaction_url(UserTransaction.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new UserTransaction' do
        expect do
          post user_transactions_url, params: { user_transaction: invalid_attributes }
        end.to change(UserTransaction, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post user_transactions_url, params: { user_transaction: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested user_transaction' do
        user_transaction = UserTransaction.create! valid_attributes
        patch user_transaction_url(user_transaction), params: { user_transaction: new_attributes }
        user_transaction.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the user_transaction' do
        user_transaction = UserTransaction.create! valid_attributes
        patch user_transaction_url(user_transaction), params: { user_transaction: new_attributes }
        user_transaction.reload
        expect(response).to redirect_to(user_transaction_url(user_transaction))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        user_transaction = UserTransaction.create! valid_attributes
        patch user_transaction_url(user_transaction), params: { user_transaction: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested user_transaction' do
      user_transaction = UserTransaction.create! valid_attributes
      expect do
        delete user_transaction_url(user_transaction)
      end.to change(UserTransaction, :count).by(-1)
    end

    it 'redirects to the user_transactions list' do
      user_transaction = UserTransaction.create! valid_attributes
      delete user_transaction_url(user_transaction)
      expect(response).to redirect_to(user_transactions_url)
    end
  end
end
